### ISSUE TITLE
The price is not correct

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#10]
![0E1FECD1-341E-4F9E-BE04-865DCFD61C81](https://user-images.githubusercontent.com/124394535/223937125-6d9086ef-5ca2-438f-b9be-89bb5ca065ee.png)
![D475F0E3-E47C-44A6-9C9F-C199488E4548](https://user-images.githubusercontent.com/124394535/223937147-538a1ed4-da35-4737-b619-f10bee597989.png)

As you see here the price is 135.000 when i go inside its shows 13500

**Comment by ZateLabClients** [comment]
completed
