### ISSUE TITLE
Auto save

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#12]
https://user-images.githubusercontent.com/124394535/224318158-dd39323d-758d-4515-a5ce-9459308d7130.MOV

When i change the barcode it goes to save directly even without i save why.. 
i m in the middle of editing

**Comment by ZateLabClients** [comment]
That(almost) barcode scanner has two keyboard functions, "Paste the text" & "Press the enter key".
Try to disable the "enter key" function from scanner software installed in the system.
Am closing this issue
