### ISSUE TITLE
Layour

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#13]
![ABE47D83-2447-4072-BBF1-08B0C98C8073](https://user-images.githubusercontent.com/124394535/224416489-02b480c6-1105-4224-aec0-a7a45dc81425.png)

The layout is not correct .

**Comment by ZateLabClients** [comment]
The problem is that it depends on size and resolution of the screen. In my phones there is no problem. 
I will increase the size little bit.
