### ISSUE TITLE
customer order data history

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#29]
there is no option to track customer order history,

**Comment by ZateLabClients** [comment]
please call me related this. If there is no callback within 3 days, I will close this issue as completed

**Comment by ZateLabClients** [comment]
In Admin Panel: Goto: Sales > Orders
You can filter the orders by customer.

![image](https://user-images.githubusercontent.com/85485041/235298605-06769fda-c08e-4b79-a805-25343458c3c8.png)



![image](https://user-images.githubusercontent.com/85485041/235298635-486180a0-8402-4ceb-a708-1578cf263d20.png)

**Comment by ZateLabClients** [comment]
The history tab is used for the "Customer relation management" like call center. I also develop call center software like this

![image](https://user-images.githubusercontent.com/85485041/235298739-5d04b9ae-a776-43cb-ba54-dad94803fb8d.png)

**Comment by ZateLabClients** [comment]
Am closing this post because of no responce, You need to reopen the post later
