### ISSUE TITLE
Pre order price calculation issues.. and adding the remaining in the sheet at end

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#3]
Pre order price calculation issues.. and adding the remaining in the sheet at end

**Comment by ZateLabClients** [comment]
Ok

**Comment by ZateLabClients** [comment]
Please use title as issue tittle instead of "Animok project"

**Comment by ZateLabClients** [comment]
![image](https://user-images.githubusercontent.com/85485041/218495265-2bea75b7-9587-4c33-9207-57ccc7615207.png)
Remaining is added. But not uploaded to server.

**Comment by ZateLabClients** [comment]
Completed
