### ISSUE TITLE
issue in ios

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#37]
item out of stock but in ios its showing instock and backoffice stock is out of stock

**Comment by Animoki** [comment]
<img width="1440" alt="Screenshot 2023-05-11 at 6 47 06 PM" src="https://github.com/ZateLabClients/animok-issues/assets/124394535/8b9bdc06-8ed9-4c7b-a8f9-18d721adb843">
<img width="1440" alt="Screenshot 2023-05-11 at 6 48 23 PM" src="https://github.com/ZateLabClients/animok-issues/assets/124394535/b3fa6dd8-f926-4a94-a5b3-7fb3f9f0a0cf">

**Comment by ZateLabClients** [comment]
product_id=1551

**Comment by ZateLabClients** [comment]
fixed. Please include app screenshort if its app problem. Whats the need of posting website screenshort if the problem is in ios???
