### ISSUE TITLE
customer order item but in qty still same not minimizing the stock 

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#38]
<img width="1440" alt="Screenshot 2023-05-11 at 6 38 12 PM" src="https://github.com/ZateLabClients/animok-issues/assets/124394535/42272d7a-0e5d-4d31-808c-715be495faed">

**Comment by ZateLabClients** [comment]
product_id=2160

**Comment by ZateLabClients** [comment]
<img width="374" alt="image" src="https://github.com/ZateLabClients/animok-issues/assets/85485041/dca06827-0ce5-4829-af53-012ff8c5c45f">

To subtract qty after order, You need to make substact quantity "Yes" in the product. U can also enable this option using excel upload
