### ISSUE TITLE
not displaying how many qty in ordered in cart

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#39]
<img width="1440" alt="Screenshot 2023-05-11 at 6 47 06 PM" src="https://github.com/ZateLabClients/animok-issues/assets/124394535/12937ef8-c609-4fec-b1c8-73841df01beb">

**Comment by ZateLabClients** [comment]
Its seems like cart is empty. Please provide any video for clear understanding

**Comment by ZateLabClients** [comment]
![image](https://github.com/ZateLabClients/animok-issues/assets/85485041/e0e3522f-7964-4fdc-a596-bc8a43b2a309)


The issue not exist. Please provide more detailes
