### ISSUE TITLE
BRAND BASE NO LABEL SHOWING

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#42]
![image](https://github.com/ZateLabClients/animok-issues/assets/124394535/4672bd65-1ba5-4ad2-963b-70b4c51adacd)
![image](https://github.com/ZateLabClients/animok-issues/assets/124394535/f6f506f0-96f5-41b6-8f92-f896f01bb0d9)
 IF WE PRESSED IN BRAND BASIS ITS NOT SHOWING ANY LABEL
EXAMPLE IF I PRESSED IN BRANPRESTO THAT ITEMS NOT SHOWING ANY LABELS LIKE PRE ORDER, INSTOCK, OUTSTOCK ETC...

**Comment by ZateLabClients** [comment]
![image](https://github.com/ZateLabClients/animok-issues/assets/85485041/9f801696-6586-4737-aec3-c10552045178)


Added
