### ISSUE TITLE
POINTS FOR PRODUCTS

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#46]
POINTS FOR PRODUCTS AND HOW TO FIND CUSTOMER AND HOW TO DISPLAY IN BACK OFFICE CUSTOMER DATA'S

**Comment by Animoki** [comment]
PROVIDE POINTS PROCESS

**Comment by ZateLabClients** [comment]
Goto edit product-> Goto Reward points

![image](https://github.com/ZateLabClients/animok-issues/assets/85485041/7b9a1fef-254b-4c41-a536-6ce946f8ae71)

Here add the price of the item in points:
![image](https://github.com/ZateLabClients/animok-issues/assets/85485041/10ad6a64-179a-4807-a80e-0a63dffc7bc0)


Here add how many points customer will by purchasing this item:
![image](https://github.com/ZateLabClients/animok-issues/assets/85485041/b5eb8b40-fa9b-4570-a379-b84ab26fcac3)
