### ISSUE TITLE
CUSTOMER HISTORY PRODUCT REPORT /HISTORY

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#47]
WHERE I FIND CUSTOMER PRODUCT HISTORY AND CUSOTMER DATA REPORT

**Comment by ZateLabClients** [comment]
Call me related to this.
I told you many times to call me related to this. You didnt make a single callback till now,

**Comment by Animoki** [comment]
you told as invoice history, not a customer product history, and what about the customer data report?

**Comment by ZateLabClients** [comment]
already discussed on call how to get these detailes, . There will no option for Excel exporting of these data
