### ISSUE TITLE
NOTIFICATIONS FOR ORDER

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#48]
NOT RECEIVING ANY NOTIFICATIONS FOR ORDER IN EMAIL/WHATSAPP (FOR CUSTOMER ORDERING)

**Comment by ZateLabClients** [comment]
If customer need to receive order alerts  on whatsapp, We will need to purchase Whatsapp API. 
It will cost you $0.0341/message.
This feature is not mentioned in our agreement, So it will be added as a additional paid feature.

For email alert we are using Mailgun API services, 
Pricing for mailgun is as follows:
![image](https://github.com/ZateLabClients/animok-issues/assets/85485041/ba11e551-85fa-4468-82dd-2ff86d3953ec)


Give me reply about this
