### ISSUE TITLE
This issue for the payment and remaining 

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#5]
![B2CEB19A-8716-4B9C-B2F6-EA784C01DF3B](https://user-images.githubusercontent.com/124394535/217912221-b5ccb5c4-177e-418b-aae2-632558888dbf.jpeg)
![D53E944E-AC40-4CCC-8C28-EEE4010306F1](https://user-images.githubusercontent.com/124394535/217912236-6e770bff-273d-4aec-afb1-35d3e5a9a257.jpeg)
![82EDE762-155C-4414-A4F9-2F77A2CE3DCE](https://user-images.githubusercontent.com/124394535/217912244-8ae7669c-5ac6-49fa-848f-778d95bcef57.jpeg)

**Comment by ZateLabClients** [comment]
Completed
