### ISSUE TITLE
The price on the items

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#6]
![43585E84-54C1-4EE8-A0A1-F56014BA8232](https://user-images.githubusercontent.com/124394535/222706456-4f710605-bb12-4cc5-a98d-d980bfe741da.png)
![E717C740-28DE-40DB-AFA4-94584E3FCF45](https://user-images.githubusercontent.com/124394535/222706466-bb186ba3-ef72-4e24-9ee5-d979f8ead1ea.png)

Hello as it shows in the picture the price is 16.00 kd but when i go inside the items it shows .1600

**Comment by ZateLabClients** [comment]
completed
