### ISSUE TITLE
Pre order and in stock and sold out label

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#7]
![6FE26EAD-E05B-46BC-A550-8F75807C5487](https://user-images.githubusercontent.com/124394535/222928571-32d94538-896c-4bcf-b429-033ff7f9b61e.png)
![5C6ED209-EA2A-4499-82C6-1971634B75AB](https://user-images.githubusercontent.com/124394535/222928581-deae9431-7a03-400f-b777-2b2ad9910238.png)

please for here make the pre order - orange
Instock - green
Sold out - red

**Comment by ZateLabClients** [comment]
completed.
But after updating you app, Please verify in all pages.
