### ISSUE TITLE
Address book

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#8]
State/ Region 
Must Be linked with the city as we explained from firoz

**Comment by ZateLabClients** [comment]
Am still working on it.
In each platform i need to make changes on 3 pages
1. Address book
2. Shipping Address
3. Billing Adress

I also need to make sure it will not make any conflicts with other platforms.

**Comment by ZateLabClients** [comment]
completed on website

**Comment by ZateLabClients** [comment]
completed
