### ISSUE TITLE
Pre order and instock plus the labels

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#9]
![1B68322E-032E-42DB-8084-FA302CAE37DD](https://user-images.githubusercontent.com/124394535/223936475-a496e105-5285-492d-8f64-edbc5d9ab461.png)
![DB82D836-7634-4A88-8DB7-4C3844B3AA26](https://user-images.githubusercontent.com/124394535/223936500-bd2102ab-6915-4331-95db-b62d7601982d.png)
![0DAB8CD5-3A5C-46E3-B4E9-1F62549409EF](https://user-images.githubusercontent.com/124394535/223936503-b7f3dd90-731b-4e65-8ef8-eec314fbd5af.png)
![7E8843FF-E804-4F2F-B8B1-071B4944680B](https://user-images.githubusercontent.com/124394535/223936508-ba7c2b29-4f54-4fd7-b81f-ace0ccbad73c.png)

hello here is some issue we found that the item its show pre order in website but it shows in app as in stock 

plus the pre order , in stock and sold out they all have one color

**Comment by ZateLabClients** [comment]
completed
